# build environment
FROM node:14-alpine as build

# set working directory
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY . /app

RUN npm install -g npm

RUN npm ci && \
    npm run build

# production environment
FROM nginx:1.16.0-alpine

RUN apk add bash

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
