# build environment
FROM node:12.2.0-alpine as build

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json

# To handle 'not get uid/gid'
RUN npm config set unsafe-perm true

RUN npm install --silent
RUN npm install @vue/cli -g

COPY . /app

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /app/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx.conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
