version: "3.7"

services:
  my-app-prod:
    container_name: vue-site-prod
    build:
      context: ./app
      dockerfile: ../Dockerfile-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/certs:/certs"
