events {
}

http {

  server {
    listen 80;
    listen [::]:80;

    server_name www.peerdb.nl;
    error_page 497 https://www.peerdb.nl$request_uri;
    return 301 https://www.peerdb.nl$request_uri;
  }

  server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name www.peerdb.nl;

    ssl_certificate /certs/www.peerdb.nl/fullchain.pem;
    ssl_certificate_key /certs/www.peerdb.nl/privkey.pem;

    include /etc/nginx/mime.types;

    server_name www.peerdb.nl;

    location / {
      root   /usr/share/nginx/html;
      index  index.html index.htm;
      try_files $uri $uri/ /index.html;
    }

    location ~* \.(eot|otf|ttf|woff|woff2)$ {
      root /usr/share/nginx/html;
    }

    error_page   500 502 503 504  /50x.html;

    location = /50x.html {
      root   /usr/share/nginx/html;
    }

  }
}
