name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Builds and runs the development image
  dev:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: make up

  # Builds and runs the production image
  prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "NODE_ENV=production" > ./app/.env.prod
          make up PROD=1
